version: 0.2
env:
  exported-variables:
    - ECR_REGION
    - ECR_REPO_NAME
    - ACCOUNT_NUMBER
    - CONTAINER_NAME
    - ENV
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${ECR_REGION} --no-include-email)
      - REPOSITORY_URI=${ECR_REPO_NAME}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - apt-get update && apt-get install -y gnupg software-properties-common curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install terraform
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.12/terragrunt_linux_amd64 -o terragrunt
      - chmod u+x /usr/local/bin/terragrunt && mv terragrunt /usr/local/bin/terragrunt
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd app          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - cd ..
      - cd environments/${ENV}/ecs
      - terragrunt plan
      - terragrunt apply -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name”:"${CONTAINER_NAME},"imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
